In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'col':[1,2,3,4],
              'col2': pd.date_range('2015-01-01', periods=4)
              })

In [6]:
df.loc[4] = [4, '2012-01-01']

In [4]:
df_new = pd.DataFrame({'col':[5,6,7,8],
              'col2': pd.date_range('2015-01-01', periods=4)
              })

In [7]:
pd.concat([df, df_new], ignore_index=True)

   col                 col2
0    1  2015-01-01 00:00:00
1    2  2015-01-02 00:00:00
2    3  2015-01-03 00:00:00
3    4  2015-01-04 00:00:00
4    4           2012-01-01
5    5  2015-01-01 00:00:00
6    6  2015-01-02 00:00:00
7    7  2015-01-03 00:00:00
8    8  2015-01-04 00:00:00

In [8]:
['item_' + str(i) for i in range(0, df.shape[0])]

index_list = []
for i in range(0, df.shape[0]):
    index_list.append('item_'+str(i))

In [ ]:
df['index'] = ['item_' + str(i) for i in range(df_c0, df.shape[0])]

In [37]:
df = df.set_index('index')

In [40]:
df.loc[['item_1']]

        col                 col2
index
item_1    2  2015-01-02 00:00:00

In [41]:
df.iloc[1]

col                       2
col2    2015-01-02 00:00:00
Name: item_1, dtype: object

In [47]:
df_concat = pd.concat([df, df_new])
df_concat

   col       col2
0    1 2015-01-01
1    2 2015-01-02
2    3 2015-01-03
3    4 2015-01-04
0    5 2015-01-01
1    6 2015-01-02
2    7 2015-01-03
3    8 2015-01-04

In [54]:
df_concat.loc[3]

   col       col2
3    4 2015-01-04
3    8 2015-01-04

In [56]:
df_concat.loc[3].iloc[0]

col                       4
col2    2015-01-04 00:00:00
Name: 3, dtype: object

In [60]:
df_concat.sort_values('col', ascending=False, inplace=True)

In [62]:
A = [1,2,5,4]

In [67]:
B = A

In [68]:
B[1] = 6

In [69]:
B

[1, 6, 4, 5]

In [76]:
A = [1,2,5,4]
B = sorted(A)
A, B

([1, 2, 5, 4], [1, 2, 4, 5])

In [77]:
A.append(6)

In [78]:
A + B

[1, 2, 5, 4, 6, 1, 2, 4, 5]

In [81]:
df[['col', 'col2']]

   col       col2
0    1 2015-01-01
1    2 2015-01-02
2    3 2015-01-03
3    4 2015-01-04

In [83]:
df.columns = ['col3', 'col4']

In [89]:
df = df.rename(columns={'col3': 'col_liczba'})
df

   col_liczba       col4
0           1 2015-01-01
1           2 2015-01-02
2           3 2015-01-03
3           4 2015-01-04

In [90]:
df.rename({0: 'row_liczba'})

            col_liczba       col4
row_liczba           1 2015-01-01
1                    2 2015-01-02
2                    3 2015-01-03
3                    4 2015-01-04

In [ ]:
df[df.columns[df.dtypes=='int64']]

   col_liczba
0           1
1           2
2           3
3           4

In [102]:
df.select_dtypes(include='int64')

   col_liczba
0           1
1           2
2           3
3           4

In [103]:
df[[True, False, True, False]]

   col_liczba       col4
0           1 2015-01-01
2           3 2015-01-03

In [105]:
df[df.col_liczba > 2]

   col_liczba       col4
2           3 2015-01-03
3           4 2015-01-04

In [106]:
df.query("col_liczba > 2")

   col_liczba       col4
2           3 2015-01-03
3           4 2015-01-04

In [110]:
df[(df.col_liczba > 2) | (df.col4 < '2015-01-04') ]

   col_liczba       col4
0           1 2015-01-01
1           2 2015-01-02
2           3 2015-01-03
3           4 2015-01-04

In [113]:
df['gr'] = ['a', 'b'] * 2

In [116]:
for df_gr in df.groupby('gr'):
    print(df_gr)

('a',    col_liczba       col4 gr
0           1 2015-01-01  a
2           3 2015-01-03  a)
('b',    col_liczba       col4 gr
1           2 2015-01-02  b
3           4 2015-01-04  b)

In [117]:
df.groupby('gr').agg( 'mean')

    col_liczba       col4
gr
a          2.0 2015-01-02
b          3.0 2015-01-03

In [119]:
df.groupby('gr').agg({'col_liczba': ['sum', 'mean']})

   col_liczba
          sum mean
gr
a           4  2.0
b           6  3.0

In [ ]:
df.groupby('gr').agg(col_liczba_sum = ('col_liczba', 'sum'), 
                     col_liczba_mean = ('col_liczba', 'mean'), )

    col_liczba_sum  col_liczba_mean
gr
a                4              2.0
b                6              3.0

In [131]:
for idx, data in df.iterrows():
    # print(idx, data.col_liczba, data.col4)
    df.loc[idx, 'col_liczba'] = data.col_liczba + 2

In [138]:
df

   col_liczba       col4 gr
0           5 2015-01-01  a
1           6 2015-01-02  b
2           7 2015-01-03  a
3           8 2015-01-04  b

In [140]:
df.apply(lambda x: str(x.col_liczba) + x.gr , axis=1 )

0    5a
1    6b
2    7a
3    8b
dtype: object

In [141]:
import seaborn as sns
df_pingwinki = sns.load_dataset('penguins')

Zadanie: 

1. Jaka jest srednia waga pingwinkow wg plci i gatunku? (uwzglednij tez NaN w plci)

2. zamien wyspe na zmienna Kategoryczna. Pogrupuj dane po wyspie (zmiennej kategorycznej) oraz gatunku i oblicz: 
    * liczbe pingwinow w danej grupie
    * srednia waga pingwinkow w danej grupie
    * liczbe pingwinow danej plci w danej grupie - przy uzyciu funkcji lambda. 
    
Przetestuj jak dziala parametr `observed` w `groupby` przy zmiennej kategorycznej.

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male