In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv(r'J:/AnalizaPython/employee_data.csv')

In [14]:
df.head(2)

   yyyy-mm  employee_id sex   level       salary  fte
0  2025-10          103   F  junior  1658.509537  1.0
1  2025-10          104   M  junior  1606.448209  1.0

In [15]:
df.shape

(61, 6)

In [16]:
df.columns

Index(['yyyy-mm', 'employee_id', 'sex', 'level', 'salary', 'fte'], dtype='object')

In [17]:
df.dtypes

yyyy-mm         object
employee_id      int64
sex             object
level           object
salary         float64
fte            float64
dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   yyyy-mm      61 non-null     object
 1   employee_id  61 non-null     int64
 2   sex          61 non-null     object
 3   level        60 non-null     object
 4   salary       61 non-null     float64
 5   fte          61 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 3.0+ KB

In [19]:
df.describe()

       employee_id       salary        fte
count    61.000000    61.000000  61.000000
mean    180.180328  1659.392354   0.881148
std      48.624928   621.123031   0.191521
min     103.000000   701.464453   0.500000
25%     134.000000  1228.788537   0.750000
50%     176.000000  1606.448209   1.000000
75%     226.000000  2030.844970   1.000000
max     257.000000  3000.000000   1.000000

In [ ]:
A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

np.quantile(A, [0.05, 0.95])

KWARTYLE - 25%, 50%, 75% 100%

array([ 1.5, 10.5])

In [24]:
df.head()

   yyyy-mm  employee_id sex   level       salary   fte
0  2025-10          103   F  junior  1658.509537  1.00
1  2025-10          104   M  junior  1606.448209  1.00
2  2025-10          105   F  junior   765.189659  0.50
3  2025-10          110   F  junior  1228.788537  0.75
4  2025-10          112   F     mid  1996.799735  1.00

In [ ]:
df['sex'] # pd.Series

0     F
1     M
2     F
3     F
4     F
     ..
56    F
57    F
58    F
59    F
60    M
Name: sex, Length: 61, dtype: object

In [33]:
df[['sex']] # pd.DataFrame

   sex
0    F
1    M
2    F
3    F
4    F
..  ..
56   F
57   F
58   F
59   F
60   M

[61 rows x 1 columns]

In [38]:
df.head()

             yyyy-mm sex   level       salary   fte
employee_id
103          2025-10   F  junior  1658.509537  1.00
104          2025-10   M  junior  1606.448209  1.00
105          2025-10   F  junior   765.189659  0.50
110          2025-10   F  junior  1228.788537  0.75
112          2025-10   F     mid  1996.799735  1.00

In [37]:
df.set_index('employee_id', inplace=True)

In [39]:
df.head()

             yyyy-mm sex   level       salary   fte
employee_id
103          2025-10   F  junior  1658.509537  1.00
104          2025-10   M  junior  1606.448209  1.00
105          2025-10   F  junior   765.189659  0.50
110          2025-10   F  junior  1228.788537  0.75
112          2025-10   F     mid  1996.799735  1.00

In [41]:
df.iloc[[0]]

             yyyy-mm sex   level       salary  fte
employee_id
103          2025-10   F  junior  1658.509537  1.0

In [45]:
df.loc[[105]]

             yyyy-mm sex   level      salary  fte
employee_id
105          2025-10   F  junior  765.189659  0.5

In [54]:
## dodawanie wiersza
df.loc[1] = {'yyyy-mm':'2025-10'}

In [55]:
df

             yyyy-mm  sex   level        salary   fte
employee_id
103          2025-10    F  junior   1658.509537  1.00
104          2025-10    M  junior   1606.448209  1.00
105          2025-10    F  junior    765.189659  0.50
110          2025-10    F  junior   1228.788537  0.75
112          2025-10    F     mid   1996.799735  1.00
...              ...  ...     ...           ...   ...
249          2025-10    F  junior   1471.435449  1.00
255          2025-10    F     mid   1967.501773  1.00
257          2025-10    M  junior    744.965164  0.50
0            2025-10    F     NaN  10005.000000  0.50
1            2025-10  NaN     NaN           NaN   NaN

[63 rows x 5 columns]

In [48]:
df.iloc[0]

yyyy-mm        2025-10
sex                  F
level           junior
salary     1658.509537
fte                1.0
Name: 103, dtype: object

In [50]:
df.loc[0]

yyyy-mm    2025-10
sex              F
level          NaN
salary     10000.0
fte            0.5
Name: 0, dtype: object

In [61]:
np.arange(1, 3)

array([1, 2])

In [62]:
## Dodawanie kolumny:
df['liczba'] = 1
df['kolejne_liczba'] = np.arange(1, df.shape[0]+1)

In [ ]:
df[['level', 'liczba', 'salary']]

              level  liczba        salary
employee_id
103          junior       1   1658.509537
104          junior       1   1606.448209
105          junior       1    765.189659
110          junior       1   1228.788537
112             mid       1   1996.799735
...             ...     ...           ...
249          junior       1   1471.435449
255             mid       1   1967.501773
257          junior       1    744.965164
0               NaN       1  10005.000000
1               NaN       1           NaN

[63 rows x 3 columns]

In [68]:
print(df['liczba'].sum())
print(df.liczba.sum())

63
63

In [70]:
df.loc[105, 'liczba'] = 2

In [71]:
df.loc[105]

yyyy-mm              2025-10
sex                        F
level                 junior
salary            765.189659
fte                      0.5
liczba                     2
kolejne_liczba             3
Name: 105, dtype: object

In [ ]:
df[(df['level'] == 'junior') & (df['salary'] > 1000)]

In [ ]:
df.query("level == 'junior' and salary > 1000")
## kolumn ze spacja trzeba uzyc `nazwa kolumny ze spacja`

ZADANKA: 

1. Jaka jest suma dla kolumny Salary?
2. Jaka jest suma dla kolumny Salary z podzialem na:
    1. kobiety i mezczyzn
    2. z podzialem na level
3. ile wynosi srednia pensja dla kobiet ktore sa juniorem, a ile mediana?

In [ ]:
print('suma kolumny salary: ', df['salary'].sum())

suma kloumny salary:  111227.93361621033

In [ ]:
print('suma kolumny salary dla Kobiet: ', df.query("sex == 'F'")['salary'].sum())
print('suma kolumny salary dla Kobiet: ', df.query("sex == 'M'")['salary'].sum())

for lev in ['junior', 'mid', 'senior']:
    print(f'suma kolumny salary dla {lev}', {df.query(f"level == {lev!r}")["salary"].sum()})

suma kolumny salary dla Kobiet:  57579.8031727066
suma kolumny salary dla Kobiet:  53648.13044350374
suma kolumny salary dla junior {np.float64(36335.7614193828)}
suma kolumny salary dla mid {np.float64(36154.82177206514)}
suma kolumny salary dla senior {np.float64(25732.350424762386)}

In [100]:
df_jm = df.query("level == 'junior' and sex == 'F'")['salary']
print('srednia:', df_jm.mean())
print('mediana: ', df_jm.median())

srednia: 1122.96568715273
mediana:  1129.4922937756066

In [101]:
df.level.unique()

array(['junior', 'mid', 'senior', nan], dtype=object)

In [103]:
df.level.value_counts(dropna=False)

level
junior    30
mid       20
senior    10
NaN        3
Name: count, dtype: int64

In [ ]:
## usuwanie kolumn i wierszy

df.drop(0, inplace=True)
df = df.drop(0)

In [106]:
df.drop(columns=['liczba'], inplace=True)

In [ ]:
print(df['salary'].sum())
print(df.head())
display(df.head())