In [114]:
import pandas as pd
import numpy as np
import seaborn as sns

# Zmiana Typow

Aby sprawdzic typ kolumny w Pandas, można użyć następujących metod:
* dataFrame.dtypes
* dataFrame.info()  
* dataFrame.\<columna\>.dtype

Zmiana typu kolumny w Pandas można wykonać na kilka sposobów:

* pd.to_datetime https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
* pd.to_numeric https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html
* pd.to_timedelta https://pandas.pydata.org/docs/reference/api/pandas.to_timedelta.html
* <dataFrame>[<columna>].astype(<nazwa typu>)

Dokumentacja:
 https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes
 https://pandas.pydata.org/docs/reference/arrays.html#api-arrays-integer-na

In [115]:
s = pd.Series([1,2,3,4,np.nan])
print('Typ wybrany przez Pandasa: ', s.dtypes)

print('------------------------------------------')

print("nie mozna zmienic na int - nie ma w nim nan")
try:
    s = s.astype('int64') ## int z malej litery nie dziala - nie ma nan
    print(s.dtypes)
except Exception as e:
    print(e)

print('------------------------------------------')
print("Zmiana na Int - dziala")

s = s.astype('Int64') # trzeba uzyc Int z duzej litery - 
print(s.dtypes)
print(s)

Typ wybrany przez Pandasa:  float64
------------------------------------------
nie mozna zmienic na int - nie ma w nim nan
Cannot convert non-finite values (NA or inf) to integer
------------------------------------------
Zmiana na Int - dziala
Int64
0       1
1       2
2       3
3       4
4    <NA>
dtype: Int64

In [116]:
## mozna tez podac typ przy tworzeniu zmiennej
s = pd.Series([1,2,3,4,np.nan], dtype='Int64')
print('Typ wybrany przez Pandasa: ', s.dtypes)
s

Typ wybrany przez Pandasa:  Int64

0       1
1       2
2       3
3       4
4    <NA>
dtype: Int64

# pd.Series.str
https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html#pandas.Series.str

umozliwia wykorzystywanie metod stringa w sposob zwektoryzowany (czyli szybszy obliczeniowo)

In [117]:
s = pd.Series(["A_Str_Series", "other_str_siries", "two_parts"])

In [118]:
s.len()

AttributeError: 'Series' object has no attribute 'len'

In [ ]:
s.str.len()

0    12
1    16
2     9
dtype: int64

In [ ]:
s.str.split('_')

0        [A, Str, Series]
1    [other, str, siries]
2            [two, parts]
dtype: object

In [ ]:
df = s.str.split('_', expand=True)

In [ ]:
## alternatywne rozwiazanie: 
for index, value in s.items():
    print(index, value.split("_"))

0 ['A', 'Str', 'Series']
1 ['other', 'str', 'siries']
2 ['two', 'parts']

In [ ]:
for index, value in df.iterrows():
    print(index)
    display(value.iloc[0])

0

'A'

1

'other'

2

'two'

In [ ]:
df = s.str.split('_', expand=True)
df

## jezeli chcemy je polaczyc spowrotem:

# df['combined'] = df[0] + '_' + df[1] + '_' + df[2]
# display(df)

       0      1       2
0      A    Str  Series
1  other    str  siries
2    two  parts    None

In [ ]:
df.values

array([['A', 'Str', 'Series'],
       ['other', 'str', 'siries'],
       ['two', 'parts', None]], dtype=object)

In [ ]:
'_'.join(df.values[2])

TypeError: sequence item 2: expected str instance, NoneType found

#### Apply
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply

Apply a function along an axis of the DataFrame.

axis{0 or ‘index’, 1 or ‘columns’}, default 0
Axis along which the function is applied:

* 0 or ‘index’: apply function to each column.

* 1 or ‘columns’: apply function to each row.

In [ ]:
df = s.str.split('_', expand=True)
df['combined'] = df.apply(lambda row: '_'.join(row.values.astype(str)), axis=1)
# lub 
df['combined'] = df[[0,1,2]].apply(lambda row: '_'.join(row.values.astype(str)), axis=1)

df['combined'] = df[[0,1,2]].apply(lambda row: '_'.join(row[row.notna()].values.astype(str)), axis=1)
df

       0      1       2          combined
0      A    Str  Series      A_Str_Series
1  other    str  siries  other_str_siries
2    two  parts    None         two_parts

In [ ]:
def funckcja1(a, b):
    return (a + b) * a

lambda a, b: (a + b) * a

In [ ]:
df = s.str.split('_', expand=True)
display(df)

def join_str(x):
    return '_'.join(x.values.astype(str))

df['combined'] = df.apply(lambda x: '_'.join(x.values.astype(str)), axis=1)
df

       0      1       2
0      A    Str  Series
1  other    str  siries
2    two  parts    None

       0      1       2          combined
0      A    Str  Series      A_Str_Series
1  other    str  siries  other_str_siries
2    two  parts    None    two_parts_None

1. Wykorzystaj funkcje apply i lambda ktora stworzy nowa kolumne w df z drugim elementtem stringa z kolumny df[combined]

2. Uzywaja apply i lambdy polacz ze soba kolumne 0 i 1
3. Uzywaja apply i lambdy polacz ze soba kolumne 1 i 2; Jezeli w kol 2 wartosc jest Null, zamien ja na string 'BRAK'

lambda x: <co zwrocic jesli warunek prawdziwy> if <warunek> else <w przeciwnym przypadku>

In [ ]:
df['odp3'] = df.apply(lambda row: row[1] + 'BRAK' if pd.isna(row[2]) else row[1] + row[2], axis=1 )

In [ ]:
## odp do 1:
## wersja 1: 
df['wer1'] = df.apply(lambda row: row['combined'].split('_')[1], axis = 1)
# wersja 2
df['wer2'] = df['combined'].apply(lambda x: x.split('_')[1])

display(df)

       0      1       2          combined   wer1   wer2
0      A    Str  Series      A_Str_Series    Str    Str
1  other    str  siries  other_str_siries    str    str
2    two  parts    None    two_parts_None  parts  parts

In [ ]:
# odp2:
df['odp2'] = df.apply(lambda row: '_'.join([row[0], row[1]]), axis = 1)

# df['odp2'] = df.apply(lambda row: row[0] +'_' + row[1], axis = 1) - mozna tez z plusem

df

       0      1       2          combined   wer1   wer2       odp2
0      A    Str  Series      A_Str_Series    Str    Str      A_Str
1  other    str  siries  other_str_siries    str    str  other_str
2    two  parts    None    two_parts_None  parts  parts  two_parts

# Groupby

In [ ]:
df_pingwinki = sns.load_dataset('penguins')

In [ ]:
df_pingwinki

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

### Metoda 1:
* `df.groupby(<column(s)>).<funkcja>`
* `df.groupby(<column(s)>)[<column(s)>].<funkcja>`

In [ ]:
## liczba obserwacji na kazdej wyspie
df_pingwinki.groupby('island').size()

island
Biscoe       168
Dream        124
Torgersen     52
dtype: int64

In [ ]:
## ale juz count, mean, sum... podsumuje kazda kolumne
df_pingwinki.groupby('island').count()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
island,,,,,,
Biscoe,168,167,167,167,167,163
Dream,124,124,124,124,124,123
Torgersen,52,51,51,51,51,47

In [ ]:
list(df_pingwinki.dtypes[df_pingwinki.dtypes != 'object'].index)

['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']

In [ ]:
## mean zwroci blad bo niektore kolumny sa tekstowe
df_pingwinki.groupby('island')[list(df_pingwinki.dtypes[df_pingwinki.dtypes != 'object'].index)].mean()

           bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
island
Biscoe          45.257485      15.874850         209.706587  4716.017964
Dream           44.167742      18.344355         193.072581  3712.903226
Torgersen       38.950980      18.429412         191.196078  3706.372549

**Cwiczenie:**

jak zadziala sum?

In [ ]:
df_pingwinki.groupby('island')[['bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm']].mean()

           bill_length_mm  bill_depth_mm  flipper_length_mm
island
Biscoe          45.257485      15.874850         209.706587
Dream           44.167742      18.344355         193.072581
Torgersen       38.950980      18.429412         191.196078

### Metoda 2:
* `df.groupby(<column(s)>).agg({'kolumna': ['funkcja1', 'funkcja2', ..], ... })`

In [ ]:
df_gr = df_pingwinki.groupby('island').agg({'bill_length_mm': ['mean', 'sum'],
                                   'species': ['nunique'],
                                   'sex': ['count']})

In [ ]:
df_gr

          bill_length_mm         species   sex
                    mean     sum nunique count
island
Biscoe         45.257485  7558.0       2   163
Dream          44.167742  5476.8       2   123
Torgersen      38.950980  1986.5       1    47

In [ ]:
df_gr.columns

MultiIndex([('bill_length_mm',    'mean'),
            ('bill_length_mm',     'sum'),
            (       'species', 'nunique'),
            (           'sex',   'count')],
           )

In [ ]:
print(df_gr.loc['Biscoe'])
display(df_gr.loc[['Biscoe']])

In [ ]:
df_gr['bill_length_mm','mean']

island
Biscoe       45.257485
Dream        44.167742
Torgersen    38.950980
Name: (bill_length_mm, mean), dtype: float64

In [ ]:
df_gr.loc['Biscoe', ('bill_length_mm','mean')]

np.float64(45.25748502994012)

In [ ]:
df_gr.columns = ['_'.join(col) for col in df_gr.columns]

In [ ]:
df_gr

           bill_length_mm_mean  bill_length_mm_sum  species_nunique  sex_count
island
Biscoe               45.257485              7558.0                2        163
Dream                44.167742              5476.8                2        123
Torgersen            38.950980              1986.5                1         47

**CWICZENIE** 

Dla kazdego gatunku i plci policz: 
* na ilu wyspach wystepuje; 
* jaka jest srednia i suma masy ciala,
* ile mamy osobnikow w danej grupie

In [ ]:
df_pingwinki['count'] = 1

In [ ]:
df_pingwinki.groupby(["species", "sex"]).agg({'island': ['nunique', 'count'],
                                              'body_mass_g': ['mean', 'sum']
                                              })

                  island        body_mass_g
                 nunique count         mean       sum
species   sex
Adelie    Female       3    73  3368.835616  245925.0
          Male         3    73  4043.493151  295175.0
Chinstrap Female       1    34  3527.205882  119925.0
          Male         1    34  3938.970588  133925.0
Gentoo    Female       1    58  4679.741379  271425.0
          Male         1    61  5484.836066  334575.0

### Metoda 3:

```<dataFrame>.groupby([<column(s)>]).agg(nowa_nazwa_kolumny = ('<kolumna z df>', 'funkcja agg), ...)```

In [ ]:
## mozemy tez zdefiniowac wlasna fuckcje: musi ona brac jako argument pd.Series i zwracac wartosc zagregowana np:

def count_female(x: pd.Series):
    return (x=='Female').sum()

In [ ]:
df_pingwinki.groupby('island').agg(bill_length_mean = ('bill_length_mm', 'mean'),
                                   unique_species = ('species', 'nunique'),
                                   count = ('sex', 'count'),
                                   count_female = ('sex', count_female))

           bill_length_mean  unique_species  count  count_female
island
Biscoe            45.257485               2    163            80
Dream             44.167742               2    123            61
Torgersen         38.950980               1     47            24

In [ ]:
for g in df_pingwinki.groupby('island'):
    print(g)

('Biscoe',     species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
20   Adelie  Biscoe            37.8           18.3              174.0
21   Adelie  Biscoe            37.7           18.7              180.0
22   Adelie  Biscoe            35.9           19.2              189.0
23   Adelie  Biscoe            38.2           18.1              185.0
24   Adelie  Biscoe            38.8           17.2              180.0
..      ...     ...             ...            ...                ...
339  Gentoo  Biscoe             NaN            NaN                NaN
340  Gentoo  Biscoe            46.8           14.3              215.0
341  Gentoo  Biscoe            50.4           15.7              222.0
342  Gentoo  Biscoe            45.2           14.8              212.0
343  Gentoo  Biscoe            49.9           16.1              213.0

     body_mass_g     sex  count
20        3400.0  Female      1
21        3600.0    Male      1
22        3800.0  Female      1
23        3950.0    Male      1
24        3800.0    Male      1
..           ...     ...    ...
339          NaN     NaN      1
340       4850.0  Female      1
341       5750.0    Male      1
342       5200.0  Female      1
343       5400.0    Male      1

[168 rows x 8 columns])
('Dream',        species island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
30      Adelie  Dream            39.5           16.7              178.0
31      Adelie  Dream            37.2           18.1              178.0
32      Adelie  Dream            39.5           17.8              188.0
33      Adelie  Dream            40.9           18.9              184.0
34      Adelie  Dream            36.4           17.0              195.0
..         ...    ...             ...            ...                ...
215  Chinstrap  Dream            55.8           19.8              207.0
216  Chinstrap  Dream            43.5           18.1              202.0
217  Chinstrap  Dream            49.6           18.2              193.0
218  Chinstrap  Dream            50.8           19.0              210.0
219  Chinstrap  Dream            50.2           18.7              198.0

     body_mass_g     sex  count
30        3250.0  Female      1
31        3900.0    Male      1
32        3300.0  Female      1
33        3900.0    Male      1
34        3325.0  Female      1
..           ...     ...    ...
215       4000.0    Male      1
216       3400.0  Female      1
217       3775.0    Male      1
218       4100.0    Male      1
219       3775.0  Female      1

[124 rows x 8 columns])
('Torgersen',     species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
5    Adelie  Torgersen            39.3           20.6              190.0
6    Adelie  Torgersen            38.9           17.8              181.0
7    Adelie  Torgersen            39.2           19.6              195.0
8    Adelie  Torgersen            34.1           18.1              193.0
9    Adelie  Torgersen            42.0           20.2              190.0
10   Adelie  Torgersen            37.8           17.1              186.0
11   Adelie  Torgersen            37.8           17.3              180.0
12   Adelie  Torgersen            41.1           17.6              182.0
13   Adelie  Torgersen            38.6           21.2              191.0
14   Adelie  Torgersen            34.6           21.1              198.0
15   Adelie  Torgersen            36.6           17.8              185.0
16   Adelie  Torgersen            38.7           19.0              195.0
17   Adelie  Torgersen            42.5           20.7              197.0
18   Adelie  Torgersen            34.4           18.4              184.0
19   Adelie  Torgersen            46.0           21.5              194.0
68   Adelie  Torgersen            35.9           16.6              190.0
69   Adelie  Torgersen            41.8           19.4              198.0
70   Adelie  Torgersen            33.5           19.0              190.0
71   Adelie  Torgersen            39.7           18.4              190.0
72   Adelie  Torgersen            39.6           17.2              196.0
73   Adelie  Torgersen            45.8           18.9              197.0
74   Adelie  Torgersen            35.5           17.5              190.0
75   Adelie  Torgersen            42.8           18.5              195.0
76   Adelie  Torgersen            40.9           16.8              191.0
77   Adelie  Torgersen            37.2           19.4              184.0
78   Adelie  Torgersen            36.2           16.1              187.0
79   Adelie  Torgersen            42.1           19.1              195.0
80   Adelie  Torgersen            34.6           17.2              189.0
81   Adelie  Torgersen            42.9           17.6              196.0
82   Adelie  Torgersen            36.7           18.8              187.0
83   Adelie  Torgersen            35.1           19.4              193.0
116  Adelie  Torgersen            38.6           17.0              188.0
117  Adelie  Torgersen            37.3           20.5              199.0
118  Adelie  Torgersen            35.7           17.0              189.0
119  Adelie  Torgersen            41.1           18.6              189.0
120  Adelie  Torgersen            36.2           17.2              187.0
121  Adelie  Torgersen            37.7           19.8              198.0
122  Adelie  Torgersen            40.2           17.0              176.0
123  Adelie  Torgersen            41.4           18.5              202.0
124  Adelie  Torgersen            35.2           15.9              186.0
125  Adelie  Torgersen            40.6           19.0              199.0
126  Adelie  Torgersen            38.8           17.6              191.0
127  Adelie  Torgersen            41.5           18.3              195.0
128  Adelie  Torgersen            39.0           17.1              191.0
129  Adelie  Torgersen            44.1           18.0              210.0
130  Adelie  Torgersen            38.5           17.9              190.0
131  Adelie  Torgersen            43.1           19.2              197.0

     body_mass_g     sex  count
0         3750.0    Male      1
1         3800.0  Female      1
2         3250.0  Female      1
3            NaN     NaN      1
4         3450.0  Female      1
5         3650.0    Male      1
6         3625.0  Female      1
7         4675.0    Male      1
8         3475.0     NaN      1
9         4250.0     NaN      1
10        3300.0     NaN      1
11        3700.0     NaN      1
12        3200.0  Female      1
13        3800.0    Male      1
14        4400.0    Male      1
15        3700.0  Female      1
16        3450.0  Female      1
17        4500.0    Male      1
18        3325.0  Female      1
19        4200.0    Male      1
68        3050.0  Female      1
69        4450.0    Male      1
70        3600.0  Female      1
71        3900.0    Male      1
72        3550.0  Female      1
73        4150.0    Male      1
74        3700.0  Female      1
75        4250.0    Male      1
76        3700.0  Female      1
77        3900.0    Male      1
78        3550.0  Female      1
79        4000.0    Male      1
80        3200.0  Female      1
81        4700.0    Male      1
82        3800.0  Female      1
83        4200.0    Male      1
116       2900.0  Female      1
117       3775.0    Male      1
118       3350.0  Female      1
119       3325.0    Male      1
120       3150.0  Female      1
121       3500.0    Male      1
122       3450.0  Female      1
123       3875.0    Male      1
124       3050.0  Female      1
125       4000.0    Male      1
126       3275.0  Female      1
127       4300.0    Male      1
128       3050.0  Female      1
129       4000.0    Male      1
130       3325.0  Female      1
131       3500.0    Male      1  )

In [ ]:
def count_sex(x, sex):
    return (x==sex).sum()

df_pingwinki.groupby('island').agg(bill_length_mean = ('bill_length_mm', 'mean'),
                                   unique_species = ('species', 'nunique'),
                                   count = ('sex', 'count'),
                                   count_female = ('sex', lambda x: count_sex(x, 'Female')),
                                   count_male = ('sex', lambda x: count_sex(x, 'Male'))
                                  )

           bill_length_mean  unique_species  count  count_female  count_male
island
Biscoe            45.257485               2    163            80          83
Dream             44.167742               2    123            61          62
Torgersen         38.950980               1     47            24          23

### Co jeszcze warto wiedziec

In [ ]:
## aby pokazac nan:
# df_pingwinki.groupby('sex').size()
df_pingwinki.groupby('sex', dropna=False).size()

sex
Female    165
Male      168
NaN        11
dtype: int64

In [ ]:
## zmienmy wyspe na zmienna kategoryczna:
df_pingwinki['island_cat'] = pd.Categorical(df_pingwinki['island'])

In [ ]:
display(df_pingwinki.groupby(['species', 'island_cat'], observed=True).size())
display(df_pingwinki.groupby(['species', 'island_cat'], observed=False).size())


## warning jest zwiazany z nadchodzaca zmiana w pandas 3

species    island_cat
Adelie     Biscoe         44
           Dream          56
           Torgersen      52
Chinstrap  Dream          68
Gentoo     Biscoe        124
dtype: int64

species    island_cat
Adelie     Biscoe         44
           Dream          56
           Torgersen      52
Chinstrap  Biscoe          0
           Dream          68
           Torgersen       0
Gentoo     Biscoe        124
           Dream           0
           Torgersen       0
dtype: int64

In [ ]:
df_pingwinki.query('species=="Chinstrap"').groupby('island', observed=True).size()

island
Dream    68
dtype: int64

In [ ]:
df_pingwinki.query('species=="Chinstrap"').groupby('island_cat', observed=False).size()

island_cat
Biscoe        0
Dream        68
Torgersen     0
dtype: int64


**Cwiczenie** 

W podziale na wyspe i gatunek policz ile pingwinkow ma bill_length_mm wieksze od 40, oraz jaka jest minimalna i maksymalna masa ciala wszystkich pingwinowk w danej grupie.
* ile jest takich pingwinkow (z dlugoscia dzioba mieksza od 40) z wyspy  'Biscoe' z gatunku 'Adelie' (oczywiscie chodzi o wypisanie wyniku w postaci jednej liczby a nie przeczytanie z tabeli.)

In [ ]:
A = pd.Series([True, False, np.nan])
print('suma:', A.sum())
print('count:',  A.count())

suma: 1
count: 2

In [ ]:
def dziob_40plus(x):
    return (x>40).sum()

df_gr = df_pingwinki.groupby(['island', 'species']).agg(
    dziob_40plus_cnt = ('bill_length_mm', dziob_40plus),
    dziob_40plus_cnt_l = ('bill_length_mm', lambda x: (x > 40).sum()),
    body_mass_max = ('body_mass_g', 'max'),
    body_mass_min = ('body_mass_g', 'min'))

In [ ]:
df_gr.index

MultiIndex([(   'Biscoe',    'Adelie'),
            (   'Biscoe',    'Gentoo'),
            (    'Dream',    'Adelie'),
            (    'Dream', 'Chinstrap'),
            ('Torgersen',    'Adelie')],
           names=['island', 'species'])

In [ ]:
print(df_gr.loc['Biscoe', 'Adelie']['dziob_40plus_cnt'])
print(df_gr.loc[('Biscoe', 'Adelie'), 'dziob_40plus_cnt'])

16.0
16

In [ ]:
df_gr

In [ ]:
df_gr = df_gr.reset_index()

df_gr.set_index('island')

,species,dziob_40plus_cnt,dziob_40plus_cnt_l,body_mass_max,body_mass_min
island,,,,,
Biscoe,Adelie,16,16,4775.0,2850.0
Biscoe,Gentoo,123,123,6300.0,3950.0
Dream,Adelie,17,17,4650.0,2900.0
Dream,Chinstrap,68,68,4800.0,2700.0
Torgersen,Adelie,18,18,4700.0,2900.0

In [ ]:
df_gr.reset_index()

## df_gr.set_index - ustawia index

,island,species,dziob_40plus_cnt,dziob_40plus_cnt_l,body_mass_max,body_mass_min
0,Biscoe,Adelie,16,16,4775.0,2850.0
1,Biscoe,Gentoo,123,123,6300.0,3950.0
2,Dream,Adelie,17,17,4650.0,2900.0
3,Dream,Chinstrap,68,68,4800.0,2700.0
4,Torgersen,Adelie,18,18,4700.0,2900.0

In [ ]:
df_pingwinki

## Merge
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html#pandas.DataFrame.merge

* istnieje tez `join` ale umozliwia laczenie tylko po wspolnej kolumnie https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join

In [119]:
df_mean_mass = df_pingwinki.groupby(['species'])[['body_mass_g']].agg('mean')

In [121]:
df_pingwinki.merge(df_mean_mass,how='inner', left_on=['species'], right_index=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g_x,sex,count,island_cat,body_mass_g_y
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,1,Torgersen,3700.662252
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,1,Torgersen,3700.662252
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,1,Torgersen,3700.662252
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,Torgersen,3700.662252
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1,Torgersen,3700.662252
...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,1,Biscoe,5076.016260
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,1,Biscoe,5076.016260
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,1,Biscoe,5076.016260
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,1,Biscoe,5076.016260
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,1,Biscoe,5076.016260

In [120]:
df_mean_mass

           body_mass_g
species
Adelie     3700.662252
Chinstrap  3733.088235
Gentoo     5076.016260

In [123]:
df_pingwinki.merge(df_mean_mass,how='inner', left_on=['species'], right_index=True, suffixes=['', '_mean'])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,count,island_cat,body_mass_g_mean
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,1,Torgersen,3700.662252
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,1,Torgersen,3700.662252
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,1,Torgersen,3700.662252
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,Torgersen,3700.662252
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1,Torgersen,3700.662252
...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,1,Biscoe,5076.016260
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,1,Biscoe,5076.016260
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,1,Biscoe,5076.016260
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,1,Biscoe,5076.016260
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,1,Biscoe,5076.016260

**Cwiczenie**

Policz srednia mase pingwikow w podziale na gatunek i plec i polacz dane z wyjsciowa tabele df_pingwinki.
* Czy po mergu liczba wierszy jest taka sama jak w wyjsciowej tabeli?

In [133]:
df_mean_mass2 = df_pingwinki.groupby(['species', 'sex'])[['body_mass_g']].agg('mean')
df_pingwinki.merge(df_mean_mass2, how='inner', left_on=['species', 'sex'], right_index=True, suffixes=['', '_mean']) ## inner- 333 rekordy, bo Nulle w sex
df_pingwinki.merge(df_mean_mass2, how='left', left_on=['species', 'sex'], right_index=True, suffixes=['', '_mean']) ## inner- 333 rekordy, bo Nulle w sex

MergeError: Must pass "right_on" OR "right_index".

In [129]:
df_mean_mass2r = df_mean_mass2.reset_index()
df_mean_mass2r
df_pingwinki.merge(df_mean_mass2,how='left', left_on=['species', 'sex'], right_on=['species', 'sex'], suffixes=['', '_mean']) ## inner- 333 rekordy, bo Nulle w sex
df_pingwinki.merge(df_mean_mass2,how='left', on=['species', 'sex'], suffixes=['', '_mean']) ## inner- 333 rekordy, bo Nulle w sex

     species     sex  body_mass_g
0     Adelie  Female  3368.835616
1     Adelie    Male  4043.493151
2  Chinstrap  Female  3527.205882
3  Chinstrap    Male  3938.970588
4     Gentoo  Female  4679.741379
5     Gentoo    Male  5484.836066

In [130]:
df_mean_mass2

                  body_mass_g
species   sex
Adelie    Female  3368.835616
          Male    4043.493151
Chinstrap Female  3527.205882
          Male    3938.970588
Gentoo    Female  4679.741379
          Male    5484.836066

In [134]:
df_pingwinki2 = df_pingwinki.set_index(['species', 'sex'])

In [139]:
df_pingwinki2.join(df_mean_mass2, on=['species', 'sex'] , how='left', rsuffix='_mean' )

                   island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
species sex
Adelie  Male    Torgersen            39.1           18.7              181.0
        Female  Torgersen            39.5           17.4              186.0
        Female  Torgersen            40.3           18.0              195.0
        NaN     Torgersen             NaN            NaN                NaN
        Female  Torgersen            36.7           19.3              193.0
...                   ...             ...            ...                ...
Gentoo  NaN        Biscoe             NaN            NaN                NaN
        Female     Biscoe            46.8           14.3              215.0
        Male       Biscoe            50.4           15.7              222.0
        Female     Biscoe            45.2           14.8              212.0
        Male       Biscoe            49.9           16.1              213.0

                body_mass_g  count island_cat  body_mass_g_mean
species sex
Adelie  Male         3750.0      1  Torgersen       4043.493151
        Female       3800.0      1  Torgersen       3368.835616
        Female       3250.0      1  Torgersen       3368.835616
        NaN             NaN      1  Torgersen               NaN
        Female       3450.0      1  Torgersen       3368.835616
...                     ...    ...        ...               ...
Gentoo  NaN             NaN      1     Biscoe               NaN
        Female       4850.0      1     Biscoe       4679.741379
        Male         5750.0      1     Biscoe       5484.836066
        Female       5200.0      1     Biscoe       4679.741379
        Male         5400.0      1     Biscoe       5484.836066

[344 rows x 8 columns]